### ISSUE TITLE
Cannot find module 'xpc-connection'

### ISSUE THREAD

**Issue by asha-blue** [romanrandom/ble-osc#3]
Hi Roman,

I seem to get a problem with the npm install to do with the xpc-connection. Is this something that I should have installed?

Any help would be great...

Thanks,

Asha

**Comment by wabisabit** [comment]
Probably it's a dependency that should be installed when you run `npm install`. What error message do you get?

**Comment by asha-blue** [comment]
I think it is my problem and that maybe I need to upgrade from Yosemite to be able to get xcode 7 but below is what I get. I am not really used to installing via the terminal so something could have gone wrong with my install of npm

Edit: I have removed the mass of errors from the above set-up as I have now install Mac OS Sierra and XCode 7. I don't get the same errors and something appears to be working.

However this seems to be happening

> Disconnected from MLT-BT05
Discovered: MLT-BT05
Connected to MLT-BT05
Working
> 

Over and over disconnecting and connecting. Nothing shows up in the Max patch.

**Comment by asha-blue** [comment]
can't seem to get this code to be formatted as such here XD

**Comment by wabisabit** [comment]
When it says working it's supposed to be receiving the data correctly. You can check by uncommenting the `console.log` lines in the **ble-osc.js** file. I'm not sure why it would be disconnecting and connecting all the time. I have only tested it with one specific combination of hardware...

**Comment by wabisabit** [comment]
I will close this issue since you solved the original one. Feel free to open another one.

**Comment by asha-blue** [comment]
Hi Roman,

I have the same hardware as in your github description. If I figure it out
I will pop it on the github.

Thanks :)
